# Adapt logs to other processes
ErrorLogFormat "%{cu}t %l apache2/%m: %M"
ErrorLogFormat connection "%{cu}t info apache2/connection: [%v:%{C}L] %a -\> %A"
ErrorLog /proc/self/fd/2
LogFormat "%{%F %T}t.%{usec_frac}t info apache2/access: [%v:%{C}L] %h %l %u \"%r\" %>s %b \"%{Referer}i\" \"%{User-agent}i\"" stdout
GlobalLog /proc/self/fd/1 stdout

# Listen on an other port if required from env.
Define "Port${SUITECRM_HTTP_PORT}"
<IfDefine !Port80>
  Listen ${SUITECRM_HTTP_PORT}
</IfDefine>

ServerName localhost

# Configure dedicated virtualhost for SuiteCRM
<VirtualHost *:${SUITECRM_HTTP_PORT}>
    DocumentRoot ${SUITECRM_STATE_DIR}

    <Directory ${SUITECRM_STATE_DIR}>
        AllowOverride All
        Require all granted
        DirectoryIndex index.php
    </Directory>
    CustomLog "|/usr/bin/rotatelogs -n 5 ${SUITECRM_STATE_DIR}/access.log 5M" combined
</VirtualHost>
