# Listen on an other port if required from env.
Define "Port${SUITECRM_HTTP_PORT}"
<IfDefine !Port80>
  Listen ${SUITECRM_HTTP_PORT}
</IfDefine>
ServerName ${SUITECRM_HTTP_HOST}
<VirtualHost *:${SUITECRM_HTTP_PORT}>
    ServerName ${SUITECRM_HTTP_HOST}
    DocumentRoot ${SUITECRM_STATE_DIR}

    <Directory ${SUITECRM_STATE_DIR}>
        AllowOverride All
        Require all granted
        DirectoryIndex index.php
    </Directory>

    ErrorLog /proc/self/fd/2
    CustomLog /proc/self/fd/1 combined
</VirtualHost>